MODULE DIST_GRID_CTL_MOD
CONTAINS
SUBROUTINE DIST_GRID_CTL(PGPG,KFDISTG,KPROMA,KFROM,KFLDS,PGP)

IMPLICIT NONE

INTEGER(KIND=4)          , INTENT(IN)  :: KFDISTG
REAL(KIND=8)    ,OPTIONAL, INTENT(IN)  :: PGPG(KPROMA,KFDISTG)
INTEGER(KIND=4)          , INTENT(IN)  :: KPROMA
INTEGER(KIND=4)          , INTENT(IN)  :: KFROM(KFDISTG)
INTEGER(KIND=4)          , INTENT(IN)  :: KFLDS
REAL(KIND=8)             , INTENT(OUT) :: PGP(KPROMA,KFLDS,1)

REAL(KIND=8),ALLOCATABLE :: ZRCV(:,:) 
REAL(KIND=8)    :: ZBUF(KPROMA,COUNT(KFROM(:) == 1),1)
INTEGER(KIND=4) :: JFLD,IGL1,IGL2,IOFF,JGL,ITO
INTEGER(KIND=4) :: IFLDCOUNT
INTEGER(KIND=4), ALLOCATABLE :: IOFFGP(:), IOFFA(:), ILONA(:)

PRINT *, " KFDISTG = ", KFDISTG
PRINT *, " UBOUND (ZBUF) = ", UBOUND (ZBUF)
PRINT *, " COUNT(KFROM(:) == 1) = ", COUNT(KFROM(:) == 1)
PRINT *, " KFROM = ", KFROM

STOP

END SUBROUTINE DIST_GRID_CTL
END MODULE DIST_GRID_CTL_MOD
