MODULE DIST_GRID_CTL_MOD
CONTAINS
SUBROUTINE DIST_GRID_CTL(PGPG,KFDISTG,KPROMA,KFROM,KFLDS,PGP,KSORT)

IMPLICIT NONE

! Declaration of arguments

INTEGER(KIND=4)          , INTENT(IN)  :: KFDISTG
REAL(KIND=8)    ,OPTIONAL, INTENT(IN)  :: PGPG(4096,KFDISTG)
INTEGER(KIND=4)          , INTENT(IN)  :: KPROMA
INTEGER(KIND=4)          , INTENT(IN)  :: KFROM(KFDISTG)
INTEGER(KIND=4)          , INTENT(IN)  :: KFLDS
REAL(KIND=8)             , INTENT(OUT) :: PGP(KPROMA,KFLDS,(4096-1)/KPROMA+1) 
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN), TARGET :: KSORT (:)

! Declaration of local variables


REAL(KIND=8),ALLOCATABLE :: ZRCV(:,:) 
REAL(KIND=8)    :: ZBUF(4096,COUNT(KFROM(:) == 1),1)
INTEGER(KIND=4) :: JFLD,IGL1,IGL2,IOFF,JGL,ITO
INTEGER(KIND=4) :: IFLDCOUNT
INTEGER(KIND=4) :: IPROC(1), IRCVREQ(1), IOFFPROC(1)
INTEGER(KIND=4), ALLOCATABLE :: IOFFGP(:), IOFFA(:), ILONA(:)
INTEGER(KIND=4), POINTER :: ISORT (:)

!     ------------------------------------------------------------------

STOP


IF (PRESENT (KSORT)) THEN
  ISORT => KSORT
ELSE
  ALLOCATE (ISORT (KFDISTG))
  DO JFLD = 1, KFDISTG
    ISORT (JFLD) = JFLD
  ENDDO
ENDIF


DO JGL=IGL1,IGL2-1
  ILONA(JGL)=200
  IOFFGP(JGL+1) = 300
  IOFFA(JGL+1)=IOFF+64
ENDDO
ILONA(IGL2)=400
DO JFLD=1,IFLDCOUNT
  DO JGL=IGL1,IGL2
    ZBUF(IOFFGP(JGL)+1:IOFFGP(JGL)+ILONA(JGL),JFLD,ITO) = PGPG(IOFFA(JGL):IOFFA(JGL)+ILONA(JGL)-1,JFLD)
  ENDDO
ENDDO
  
END SUBROUTINE DIST_GRID_CTL
END MODULE DIST_GRID_CTL_MOD
