SUBROUTINE EDIST_GRID(PGPG,KPROMA,KFDISTG,KFROM,KRESOL,PGP,KSORT)

USE DIST_GRID_CTL_MOD ,ONLY : DIST_GRID_CTL

IMPLICIT NONE

REAL(KIND=8)    ,OPTIONAL, INTENT(IN)  :: PGPG(:,:)
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN)  :: KPROMA
INTEGER(KIND=4) ,          INTENT(IN)  :: KFDISTG
INTEGER(KIND=4) ,          INTENT(IN)  :: KFROM(:)
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN)  :: KRESOL
REAL(KIND=8)    ,          INTENT(OUT) :: PGP(:,:,:)
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN)  :: KSORT (:)

INTEGER(KIND=4) :: IPROMA, IFLDS

WRITE (0, *) __FILE__, ':', __LINE__ 
CALL FLUSH (0)

CALL STACK

CALL DIST_GRID_CTL(PGPG,KFDISTG,IPROMA,KFROM,IFLDS,PGP)

STOP

END SUBROUTINE EDIST_GRID

