PROGRAM MASTER

USE DIST_GRID_CTL_MOD

IMPLICIT NONE

REAL (KIND=8) :: PBUF (4096, 48, 1)
REAL (KIND=8) :: ZFIELDBUF (4096,48)
INTEGER (KIND=4) :: IFROM (48), ISORT (48)
INTEGER (KIND=4) :: KFIELDG, KRESOL


INTERFACE
SUBROUTINE EDIST_GRID(PGPG,KPROMA,KFDISTG,KFROM,KRESOL,PGP,KSORT)
IMPLICIT NONE
REAL(KIND=8)    ,OPTIONAL, INTENT(IN)  :: PGPG(:,:)
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN)  :: KPROMA
INTEGER(KIND=4)          , INTENT(IN)  :: KFDISTG
INTEGER(KIND=4)          , INTENT(IN)  :: KFROM(:)
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN)  :: KRESOL
REAL(KIND=8)             , INTENT(OUT) :: PGP(:,:,:)
INTEGER(KIND=4) ,OPTIONAL, INTENT(IN)  :: KSORT (:)
END SUBROUTINE EDIST_GRID
END INTERFACE


IFROM = 1
KFIELDG = 48
KRESOL = 1

  CALL EDIST_GRID (PGPG=ZFIELDBUF,KFDISTG=KFIELDG,KFROM=IFROM,&
     & PGP=PBUF,KSORT=ISORT,KRESOL=KRESOL)


END PROGRAM MASTER
